# Generated by Django 2.2.7 on 2020-03-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_covers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='covers',
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank='True', upload_to='covers/'),
        ),
    ]
